name: anti_procrastination_app2
description: Anti Procrastination App 2 (Flutter-only focus + tasks/templates/stats)
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  sqflite: ^2.3.3+1    # 本地数据库
  path: ^1.9.0         # join() 等路径方法
  wakelock_plus: ^1.2.5
  fl_chart: ^0.66.2     # ← 新增：图表
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  flutter_timezone: ^1.0.8   # ← 新增，替代 flutter_native_timezone


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
