name: anti_procrastination_app2
description: Anti Procrastination App 2 (Flutter-only focus + tasks/templates/stats)
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  intl: ^0.19.0
  collection: ^1.18.0
  provider: ^6.1.2
  wakelock_plus: ^1.2.5
  fl_chart: ^0.66.2     # ← 新增：图表

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
