name: build-debug-apk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 先安装 Flutter，准备好 flutter 命令
      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 如果仓库里还没有完整脚手架，这一步会把缺的文件补齐（不会覆盖你已有文件）
      - name: Bootstrap Flutter project files
        run: flutter create .

      # 现在已经有 *.gradle / gradle-wrapper.properties，启用 Gradle 缓存就不会报错了
      - name: Set up Java 17 (with Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0

      - name: Fetch packages
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 14
