name: build-debug-apk

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 先安装 Flutter，待会要用 flutter create .
      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      # 补齐缺失的 android/ Gradle 脚手架（不会覆盖你已有源码）
      - name: Bootstrap Flutter project files
        run: flutter create .

      # 再装 JDK（现在已有 Gradle 文件，可以安全开启缓存）
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # 装好 Android SDK 基础工具（不再通过 packages 输入装具体包）
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 手动用 sdkmanager 安装所需平台与构建工具（关键修复！）
      - name: Install Android platforms & build-tools
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Fetch packages
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 14
